name: 🔍 CI - Apple Map
on:
  pull_request:
    branches:
      - main
    paths:
      - "apple_map/**"
      - ".github/workflows/ci-apple-map.yml"
  push:
    branches:
      - main
    paths:
      - "apple_map/**"
      - ".github/workflows/ci-apple-map.yml"
  workflow_dispatch:
jobs:
  test:
    name: 🧪 Test
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v3

      - name: 🧪 Test
        run: cd apple_map && make test
